-- SEED DATA FOR FASE 2: 150 LECCIONES ESTRUCTURADAS (50 NUTRICIÓN, 50 ENTRENAMIENTO, 50 HÁBITOS)
-- Ejecuta este script en el SQL Editor de tu proyecto en Supabase para poblar la tabla lessons_curriculum.

-- Limpiar currícula previa si existe
TRUNCATE TABLE public.lessons_curriculum CASCADE;

-- =========================================================================
-- A. CURRÍCULA DE NUTRICIÓN (50 Lecciones)
-- =========================================================================
INSERT INTO public.lessons_curriculum (id, category, sequence_number, title, topic, difficulty) VALUES
('nutrition_1', 'nutrition', 1, 'Los Macronutrientes', 'Proteínas, carbohidratos y grasas: sus funciones vitales y por qué los tres son necesarios.', 'basic'),
('nutrition_2', 'nutrition', 2, 'El Poder de las Proteínas', 'Fuentes de proteínas, reparación muscular, saciedad y su papel en mantener el metabolismo activo.', 'basic'),
('nutrition_3', 'nutrition', 3, 'Carbohidratos: Tu Energía', 'Desmitificar los carbohidratos. Carbohidratos complejos vs simples, fuentes saludables y su función como gasolina.', 'basic'),
('nutrition_4', 'nutrition', 4, 'Grasas Saludables', 'El rol de las grasas en la salud hormonal y cerebral. Fuentes buenas como aguacate, frutos secos y aceite de oliva.', 'basic'),
('nutrition_5', 'nutrition', 5, 'Fibra y Digestión', 'Qué es la fibra soluble e insoluble, cómo mejora el tránsito intestinal y su impacto en la saciedad prolongada.', 'basic'),
('nutrition_6', 'nutrition', 6, 'Hidratación Esencial', 'Importancia del agua, cuánta tomar al día, retención de líquidos y por qué el agua es la mejor bebida.', 'basic'),
('nutrition_7', 'nutrition', 7, 'Vitaminas Clave', 'Las vitaminas hidrosolubles y liposolubles, dónde encontrarlas y su función reguladora en el cuerpo.', 'basic'),
('nutrition_8', 'nutrition', 8, 'Minerales en tu Plato', 'El rol del calcio, hierro, magnesio y zinc en tus huesos, energía y sistema inmune.', 'basic'),
('nutrition_9', 'nutrition', 9, 'El Balance Energético', 'Calorías explicadas. Relación entre calorías consumidas y calorías gastadas para mantener, perder o ganar peso.', 'basic'),
('nutrition_10', 'nutrition', 10, 'El Metabolismo Basal', 'Qué es el TMB (Tasa Metabólica Basal) y cómo tu cuerpo gasta energía en reposo para mantenerse vivo.', 'basic'),
('nutrition_11', 'nutrition', 11, 'Lectura de Ingredientes', 'Regla de oro: los ingredientes se listan de mayor a menor cantidad. Identificar químicos dañinos y azúcares ocultas.', 'intermediate'),
('nutrition_12', 'nutrition', 12, 'El Truco de las Porciones', 'Cómo leer la tabla nutricional por porción y multiplicar los datos si consumes el empaque completo.', 'intermediate'),
('nutrition_13', 'nutrition', 13, 'Azúcares Ocultas', 'Los más de 50 nombres que la industria le da al azúcar (jarabe de maíz, maltodextrina, dextrosa) para despistarte.', 'intermediate'),
('nutrition_14', 'nutrition', 14, 'Grasas Trans y Saturadas', 'Cómo identificar grasas hidrogenadas y por qué las grasas trans dañan tu salud cardiovascular.', 'intermediate'),
('nutrition_15', 'nutrition', 15, 'Sodio y Retención', 'Efecto del exceso de sodio en alimentos procesados sobre la presión arterial y la retención de agua.', 'intermediate'),
('nutrition_16', 'nutrition', 16, 'Comida Real vs Procesados', 'El concepto de densidad nutricional: por qué 200 kcal de brócoli te nutren y llenan más que 200 kcal de papas fritas.', 'intermediate'),
('nutrition_17', 'nutrition', 17, 'Aceites de Cocina', 'Aceites estables al calor (oliva, coco) vs aceites vegetales refinados inflamatorios (girasol, soya, maíz).', 'intermediate'),
('nutrition_18', 'nutrition', 18, 'Mitos de los Edulcorantes', 'Edulcorantes artificiales vs naturales (estevia, eritritol). Efectos en la microbiota y control de antojos.', 'intermediate'),
('nutrition_19', 'nutrition', 19, 'Compras Inteligentes', 'Cómo hacer compras eficientes en el supermercado: ir sin hambre, comprar en el perímetro y evitar pasillos de snacks.', 'intermediate'),
('nutrition_20', 'nutrition', 20, 'El Método del Plato', 'Estructura visual ideal: 50% verduras, 25% proteína magra, 25% carbohidratos complejos.', 'intermediate'),
('nutrition_21', 'nutrition', 21, 'Porciones con la Mano', 'Uso práctico de la mano: palma para proteína, puño para vegetales, cuenco para carbohidratos, pulgar para grasas.', 'intermediate'),
('nutrition_22', 'nutrition', 22, 'Comer en Restaurantes', 'Estrategias para comer fuera: salsas aparte, agua de entrada, evitar entradas fritas y elegir proteínas magras.', 'intermediate'),
('nutrition_23', 'nutrition', 23, 'Snacks Saludables', 'Opciones rápidas y saciantes de snacks altos en proteína y fibra (frutos secos, yogur griego, frutas enteras).', 'intermediate'),
('nutrition_24', 'nutrition', 24, 'Aprende a Escuchar tu Apetito', 'Diferencia entre hambre fisiológica (estómago vacío, gradual) y hambre emocional (ansiedad, antojos rápidos).', 'intermediate'),
('nutrition_25', 'nutrition', 25, 'Masticación y Saciedad', 'Por qué masticar cada bocado 20 veces ayuda a tu digestión y le da tiempo al cerebro a registrar que estás lleno.', 'intermediate'),
('nutrition_26', 'nutrition', 26, 'Líquidos en la Comida', 'Mitos sobre si tomar agua con las comidas diluye los jugos gástricos. La moderación es la clave.', 'intermediate'),
('nutrition_27', 'nutrition', 27, 'Alcohol y Calorías Vacías', 'Efecto del alcohol en la quema de grasa, acumulación de lípidos y cómo sabotea la recuperación muscular.', 'intermediate'),
('nutrition_28', 'nutrition', 28, 'Aderezos y Calorías Ocultas', 'Salsas comerciales (mayonesa, aderezos césar) que multiplican las calorías de una ensalada sin que te des cuenta.', 'intermediate'),
('nutrition_29', 'nutrition', 29, 'Fruta Entera vs Jugo', 'Por qué comer la fruta aporta fibra y evita picos de insulina, mientras que el jugo es azúcar libre sin fibra.', 'intermediate'),
('nutrition_30', 'nutrition', 30, 'Proteína Animal vs Vegetal', 'Comparativa de digestibilidad y espectro de aminoácidos. Cómo combinar legumbres y cereales para proteínas completas.', 'intermediate'),
('nutrition_31', 'nutrition', 31, 'Nutrición Pre-Entreno', 'Qué comer antes de entrenar para tener energía (carbohidratos de fácil digestión) y evitar molestias estomacales.', 'advanced'),
('nutrition_32', 'nutrition', 32, 'Nutrición Post-Entreno', 'La ventana anabólica desmitificada. Importancia de la proteína y carbohidratos post-ejercicio para reparar músculo.', 'advanced'),
('nutrition_33', 'nutrition', 33, 'El Suplemento de Creatina', 'Qué es el monohidrato de creatina, sus beneficios probados en fuerza, masa muscular y función cognitiva.', 'advanced'),
('nutrition_34', 'nutrition', 34, 'Proteína en Polvo', 'Mitos del suero de leche (whey protein). Es un alimento práctico, no un químico mágico. Cómo elegir una limpia.', 'advanced'),
('nutrition_35', 'nutrition', 35, 'Cafeína y Rendimiento', 'Uso de la cafeína como pre-entreno: dosis efectivas, tiempos de ingesta y tolerancia individual.', 'advanced'),
('nutrition_36', 'nutrition', 36, 'Ayuno Intermitente', 'Qué es el protocolo 16/8. Beneficios en flexibilidad metabólica y control calórico. No es magia, es una herramienta.', 'advanced'),
('nutrition_37', 'nutrition', 37, 'Flexibilidad Metabólica', 'Habilidad del cuerpo para alternar eficientemente entre quemar carbohidratos y quemar grasa como energía.', 'advanced'),
('nutrition_38', 'nutrition', 38, 'Ciclado de Carbohidratos', 'Estrategia de días altos en carbohidratos (días de entrenamiento intenso) y días bajos (días de descanso).', 'advanced'),
('nutrition_39', 'nutrition', 39, 'Déficit Calórico Sostenible', 'Cómo reducir calorías sin pasar hambre extrema, evitar el efecto rebote y mantener tu masa muscular.', 'advanced'),
('nutrition_40', 'nutrition', 40, 'Superávit Calórico Limpio', 'Cómo ganar masa muscular minimizando la ganancia de grasa. Ajuste calórico ligero (+200 a +400 kcal).', 'advanced'),
('nutrition_41', 'nutrition', 41, 'Recomposición Corporal', 'Cómo perder grasa y ganar músculo al mismo tiempo. Quiénes pueden lograrlo y la importancia de la proteína.', 'advanced'),
('nutrition_42', 'nutrition', 42, 'Ciclo Menstrual y Nutrición', 'Cómo varían las necesidades calóricas y antojos según las fases del ciclo (folicular, ovulatoria, lútea).', 'advanced'),
('nutrition_43', 'nutrition', 43, 'Salud Intestinal y Microbiota', 'Efecto de la microbiota en tu sistema inmune y estado de ánimo. Probióticos (yogur, kéfir) y prebióticos.', 'advanced'),
('nutrition_44', 'nutrition', 44, 'Mitos de los Cheat Days', 'Por qué un día de comer sin control sabotea tu déficit calórico de toda la semana y cómo hacer comidas libres controladas.', 'advanced'),
('nutrition_45', 'nutrition', 45, 'Micronutrientes y Rendimiento', 'El rol de antioxidantes y electrolitos en evitar calambres y acelerar la recuperación post-entrenamiento.', 'advanced'),
('nutrition_46', 'nutrition', 46, 'Alimentos Líquidos vs Sólidos', 'La saciedad que aportan los alimentos sólidos al masticar frente a la facilidad de digerir batidos y jugos.', 'advanced'),
('nutrition_47', 'nutrition', 47, 'Omega 3 y Vitamina D', 'Suplementos esenciales de salud general: acción antiinflamatoria del Omega 3 y el rol hormonal de la Vitamina D.', 'advanced'),
('nutrition_48', 'nutrition', 48, 'Romper Estancamientos', 'Por qué dejas de perder peso (adaptación metabólica) y cómo ajustar calorías o actividad física para continuar.', 'advanced'),
('nutrition_49', 'nutrition', 49, 'Dieta Antiinflamatoria', 'Alimentos que reducen la inflamación sistémica (cúrcuma, frutos rojos, pescado azul) y cuáles evitar (azúcar, ultraprocesados).', 'advanced'),
('nutrition_50', 'nutrition', 50, 'Nutrición y Longevidad', 'Hábitos alimenticios asociados a una vida más larga y saludable: restricción calórica moderada y densidad nutricional.', 'advanced');

-- =========================================================================
-- B. CURRÍCULA DE ENTRENAMIENTO (50 Lecciones)
-- =========================================================================
INSERT INTO public.lessons_curriculum (id, category, sequence_number, title, topic, difficulty) VALUES
('training_1', 'training', 1, 'Fuerza vs. Cardio', 'Por qué el entrenamiento de fuerza es el rey para la composición corporal y salud, y el cardio es su complemento.', 'basic'),
('training_2', 'training', 2, 'Hipertrofia Explicada', 'Cómo crecen los músculos: tensión mecánica, daño muscular y estrés metabólico en palabras sencillas.', 'basic'),
('training_3', 'training', 3, 'El Concepto de RIR', 'Repeticiones en Reserva: cómo autoevaluar la intensidad de tus series y quedarte cerca del fallo (RIR 1-3).', 'basic'),
('training_4', 'training', 4, 'Calentamiento Dinámico', 'Evita estiramientos estáticos antes de entrenar. Ejercicios dinámicos y series de aproximación para preparar tus articulaciones.', 'basic'),
('training_5', 'training', 5, 'Sobrecarga Progresiva', 'El principio más importante: para progresar debes aumentar peso, repeticiones o series a lo largo del tiempo.', 'basic'),
('training_6', 'training', 6, 'Frecuencia de Entrenamiento', 'Cuántas veces por semana entrenar cada músculo. Frecuencia 2 como rango óptimo para la mayoría.', 'basic'),
('training_7', 'training', 7, 'El Descanso entre Series', 'Mito de descansar 30 segundos. Por qué descansar de 1.5 a 3 minutos maximiza tu fuerza y rendimiento.', 'basic'),
('training_8', 'training', 8, 'Rango de Movimiento (ROM)', 'Hacer las repeticiones completas estirando y contrayendo el músculo vs repeticiones a medias con peso excesivo.', 'basic'),
('training_9', 'training', 9, 'Conexión Mente-Músculo', 'Concentrarse en el músculo que se está trabajando para mejorar la activación de fibras durante el set.', 'basic'),
('training_10', 'training', 10, 'Agujetas y Progreso', 'Mito: "si no duele no sirve". Por qué el dolor muscular post-entrenamiento (agujetas) no es indicador directo de progreso.', 'basic'),
('training_11', 'training', 11, 'Biomecánica: La Sentadilla', 'Técnica de sentadillas: iniciación desde la cadera, rodillas hacia afuera y evitar doblar la espalda lumbar.', 'intermediate'),
('training_12', 'training', 12, 'Biomecánica: Peso Muerto', 'Bisagra de cadera vs sentarse. Mantener la barra pegada a las piernas y la columna neutra para proteger la espalda.', 'intermediate'),
('training_13', 'training', 13, 'Biomecánica: Flexiones', 'Push-ups correctos: codos a 45 grados de tu torso (forma de flecha) en lugar de 90 grados (forma de T).', 'intermediate'),
('training_14', 'training', 14, 'Biomecánica: Remo con Mancuerna', 'Cómo jalar hacia la cadera en lugar de hacia el pecho para enfocar el esfuerzo en el dorsal ancho.', 'intermediate'),
('training_15', 'training', 15, 'Biomecánica: Planchas Abdominales', 'Activar el abdomen, evitar que caiga la pelvis y realizar retroversión pélvica para máxima contracción.', 'intermediate'),
('training_16', 'training', 16, 'Biomecánica: Zancadas / Lunges', 'Alineación de rodilla con la punta del pie, ángulo de 90 grados y torso ligeramente inclinado para enfocar glúteos.', 'intermediate'),
('training_17', 'training', 17, 'Biomecánica: Press de Hombro', 'Trayectoria de la barra, evitar arquear la espalda y mantener los codos ligeramente adelantados.', 'intermediate'),
('training_18', 'training', 18, 'Biomecánica: Press de Banca', 'Retracción escapular, arco lumbar fisiológico y bajar la barra a la línea media del pecho.', 'intermediate'),
('training_19', 'training', 19, 'Biomecánica: Elevaciones Laterales', 'Inclinación de hombros, jalar hacia los lados e inclinar ligeramente los pulgares para aislar el deltoides lateral.', 'intermediate'),
('training_20', 'training', 20, 'Biomecánica: Curl de Bíceps', 'Evitar balancear el cuerpo, mantener los codos pegados a los costados y controlar la bajada lenta.', 'intermediate'),
('training_21', 'training', 21, 'Estructura: Series y Reps', 'Cuántas series hacer por músculo a la semana (volumen). Rango de 10 a 20 series semanales por grupo muscular.', 'intermediate'),
('training_22', 'training', 22, 'Rutinas Full-Body', 'Beneficios de entrenar todo el cuerpo en cada sesión. Ideal para principiantes o personas con poco tiempo.', 'intermediate'),
('training_23', 'training', 23, 'Rutinas torso-Pierna', 'División del entrenamiento en días de tren superior y tren inferior. Excelente para intermedios.', 'intermediate'),
('training_24', 'training', 24, 'Rutinas Push-Pull-Legs', 'División avanzada: empujes (pecho, hombro, tríceps), jalones (espalda, bíceps) y piernas. Frecuencia y organización.', 'intermediate'),
('training_25', 'training', 25, 'Control de la Fase Excéntrica', 'Por qué bajar el peso de forma controlada (2-3 segundos) genera más hipertrofia que soltar el peso rápido.', 'intermediate'),
('training_26', 'training', 26, 'Ejercicios Compuestos', 'Movimientos multiarticulares (sentadillas, press banca, dominadas) que reclutan múltiples músculos a la vez.', 'intermediate'),
('training_27', 'training', 27, 'Ejercicios de Aislamiento', 'Movimientos de una sola articulación (curl bíceps, extensiones tríceps) ideales para detallar músculos cansados.', 'intermediate'),
('training_28', 'training', 28, 'Rutinas en Casa con Peso Corporal', 'Cómo progresar usando calistenia y modificaciones de ejercicios (flexiones declinadas, sentadilla búlgara).', 'intermediate'),
('training_29', 'training', 29, 'Uso de Bandas de Resistencia', 'Física de la tensión elástica: por qué la tensión aumenta al final del movimiento y cómo combinarlas.', 'intermediate'),
('training_30', 'training', 30, 'Velocidad de Ejecución (Tempo)', 'Explicación de las fases del movimiento y cómo leer números como 3-0-1-0 para regular el ritmo de la serie.', 'intermediate'),
('training_31', 'training', 31, 'Entrenamiento al Fallo Muscular', 'Qué es el fallo real y por qué no es necesario alcanzarlo en cada serie de tu entrenamiento.', 'advanced'),
('training_32', 'training', 32, 'Fatiga del Sistema Nervioso', 'Diferencia entre fatiga local muscular y fatiga sistémica acumulada del sistema nervioso central.', 'advanced'),
('training_33', 'training', 33, 'Técnica Avanzada: Drop Sets', 'Realizar una serie hasta casi el fallo, reducir el peso de inmediato un 20% y continuar sin descanso.', 'advanced'),
('training_34', 'training', 34, 'Técnica Avanzada: Superseries', 'Combinar dos ejercicios seguidos sin descanso intermedio (agonistas o antagonistas). Optimización de tiempo.', 'advanced'),
('training_35', 'training', 35, 'Técnica Avanzada: Rest-Pause', 'Serie al fallo, descanso corto de 15 segundos y hacer un par de repeticiones adicionales con el mismo peso.', 'advanced'),
('training_36', 'training', 36, 'Planificación: Deload / Descarga', 'Por qué planificar una semana de descarga reduciendo a la mitad el volumen y peso ayuda a tu recuperación y progreso.', 'advanced'),
('training_37', 'training', 37, 'Periodización del Entrenamiento', 'Cómo organizar bloques de fuerza (bajas reps, mucho peso) y bloques de volumen para evitar estancamientos.', 'advanced'),
('training_38', 'training', 38, 'El Rol del Sueño en el Músculo', 'Por qué la falta de sueño profundo destruye la testosterona, eleva el cortisol e interrumpe la síntesis proteica.', 'advanced'),
('training_39', 'training', 39, 'Salud Articular y Tendinosa', 'Cómo cuidar tus tendones y ligamentos con progresiones controladas. El dolor articular como señal de alerta.', 'advanced'),
('training_40', 'training', 40, 'Manejo del Estrés en el Gimnasio', 'El cortisol crónico compite directamente con la testosterona y reduce la capacidad de tu cuerpo para regenerar tejidos.', 'advanced'),
('training_41', 'training', 41, 'Cardio LISS vs HIIT', 'Cardio de baja intensidad estable (LISS) frente al entrenamiento interválico de alta intensidad (HIIT). Ventajas.', 'advanced'),
('training_42', 'training', 42, 'Rango de Repeticiones Óptimo', 'El mito de "6 para fuerza y 12 para definición". Todo rango de 5 a 30 repeticiones construye músculo si el RIR es bajo.', 'advanced'),
('training_43', 'training', 43, 'Entrenamiento del Core', 'Más allá de los "six-pack": estabilidad, función de transferencia de fuerza de la columna y prevención de lumbalgia.', 'advanced'),
('training_44', 'training', 44, 'Uso de Cinturón de Fuerza', 'Mitos sobre si debilita el core. Cuándo usarlo correctamente utilizando la respiración Valsalva.', 'advanced'),
('training_45', 'training', 45, 'Agarre y Accesorios', 'Correas (straps) y magnesio. Cuándo usarlos para que la falta de fuerza en el agarre no limite el trabajo de tu espalda.', 'advanced'),
('training_46', 'training', 46, 'Entrenamiento en Déficit Calórico', 'Cómo entrenar cuando estás perdiendo grasa: prioridad en mantener la fuerza para no perder tu masa muscular.', 'advanced'),
('training_47', 'training', 47, 'Entrenamiento en Superávit', 'Estrategias para empujar la fuerza al máximo cuando tu cuerpo tiene abundancia de energía calórica.', 'advanced'),
('training_48', 'training', 48, 'Falta de Progreso y Ajustes', 'Cómo auditar tu rutina si llevas semanas sin progresar en peso o repeticiones. Variables a modificar.', 'advanced'),
('training_49', 'training', 49, 'Entrenamiento Conforme Envejecemos', 'Importancia de mantener la masa muscular (sarcopenia) y fuerza en articulaciones para la autonomía de vida.', 'advanced'),
('training_50', 'training', 50, 'El Entrenamiento como Estilo de Vida', 'Construir una relación saludable con el ejercicio. Disciplina sobre motivación a largo plazo.', 'advanced');

-- =========================================================================
-- C. CURRÍCULA DE HÁBITOS Y MENTALIDAD (50 Lecciones)
-- =========================================================================
INSERT INTO public.lessons_curriculum (id, category, sequence_number, title, topic, difficulty) VALUES
('habits_1', 'habits', 1, 'Anatomía del Hábito', 'Explicación del bucle del hábito: señal, rutina y recompensa. Identificar comportamientos automáticos.', 'basic'),
('habits_2', 'habits', 2, 'Los Hábitos Atómicos', 'El poder del 1% diario: pequeños cambios acumulados que generan transformaciones masivas en un año.', 'basic'),
('habits_3', 'habits', 3, 'Diseña tu Entorno', 'Mito de la fuerza de voluntad. Por qué es mejor rediseñar tu casa (ej: no comprar galletas si quieres evitar el dulce).', 'basic'),
('habits_4', 'habits', 4, 'Asociación de Hábitos', 'Cómo anclar un nuevo hábito a uno ya existente (ej: "después de cepillarme los dientes, tomaré un vaso de agua").', 'basic'),
('habits_5', 'habits', 5, 'Consistencia vs Motivación', 'Por qué la motivación es pasajera y la consistencia (disciplina basada en sistemas) es la que da resultados.', 'basic'),
('habits_6', 'habits', 6, 'La Regla de los 2 Minutos', 'Cómo vencer la procrastinación reduciendo tu nuevo hábito a algo de 2 minutos (ej: ponte la ropa de deporte para empezar).', 'basic'),
('habits_7', 'habits', 7, 'Recompensa Inmediata', 'Cómo asociar una recompensa sana a un hábito difícil para entrenar a tu cerebro a repetirlo.', 'basic'),
('habits_8', 'habits', 8, 'El Registro de Hábitos', 'La satisfacción de marcar tu progreso diario en un calendario y por qué te motiva a no romper la cadena.', 'basic'),
('habits_9', 'habits', 9, 'Fuerza de Voluntad', 'La fuerza de voluntad como una batería finita que se agota durante el día. Evita tomar decisiones difíciles cansado.', 'basic'),
('habits_10', 'habits', 10, 'Identidad y Hábitos', 'El cambio real empieza por tu identidad: no pienses "estoy tratando de entrenar", piensa "soy un deportista".', 'basic'),
('habits_11', 'habits', 11, 'Hambre Emocional', 'Qué es comer por emociones (tristeza, aburrimiento, estrés) y cómo identificarlo frente al hambre física.', 'intermediate'),
('habits_12', 'habits', 12, 'El Ciclo de la Culpa', 'Cómo el comer emocional genera culpa, lo cual eleva el estrés y te empuja a volver a comer por ansiedad.', 'intermediate'),
('habits_13', 'habits', 13, 'Alimentación Consciente', 'Mindful eating: apagar pantallas al comer, masticar despacio y disfrutar los sabores para controlar la saciedad.', 'intermediate'),
('habits_14', 'habits', 14, 'La Regla de los 5 Minutos', 'Técnica ante un antojo: tomar agua y esperar 5 minutos haciendo otra actividad. Generalmente el antojo pasa.', 'intermediate'),
('habits_15', 'habits', 15, 'Higiene del Sueño', 'Importancia del sueño profundo para la quema de grasa y regeneración. Apagar luces azules 30 minutos antes.', 'intermediate'),
('habits_16', 'habits', 16, 'Ritmos Circadianos', 'Sincronizar tu reloj biológico: ver luz solar al despertar y oscuridad total para dormir mejora tus hormonas.', 'intermediate'),
('habits_17', 'habits', 17, 'Cortisol y Grasa', 'Cómo el estrés crónico eleva la hormona cortisol, facilitando la acumulación de grasa abdominal y la pérdida de músculo.', 'intermediate'),
('habits_18', 'habits', 18, 'Respiración Diafragmática', 'Técnica de respiración de 4 tiempos para calmar el sistema nervioso simpático ante picos de estrés.', 'intermediate'),
('habits_19', 'habits', 19, 'La Trampa de Todo o Nada', 'Evitar pensar "ya fallé hoy comiendo mal, arruinaré todo el día". Un mal bocado no arruina tu progreso.', 'intermediate'),
('habits_20', 'habits', 20, 'Autocompasión y Fallos', 'Por qué tratarse con amabilidad al fallar un hábito te ayuda a reanudarlo antes que castigarte mentalmente.', 'intermediate'),
('habits_21', 'habits', 21, 'Planificación Semanal', 'Reservar 10 minutos el domingo para organizar tus comidas y entrenamientos de la semana reduce la fatiga de decisión.', 'intermediate'),
('habits_22', 'habits', 22, 'La Regla de "No Fallar Dos Veces"', 'Si fallas un hábito un día por fuerza mayor, asegúrate bajo ninguna circunstancia de fallar al día siguiente.', 'intermediate'),
('habits_23', 'habits', 23, 'El Poder del Agua al Despertar', 'Iniciar el día rehidratando tu cerebro con un gran vaso de agua para encender tus sistemas metabólicos.', 'intermediate'),
('habits_24', 'habits', 24, 'Limitar el Acceso a Distracciones', 'Cómo alejar tu teléfono durante tus sesiones de estudio o entrenamiento para mejorar el foco mental.', 'intermediate'),
('habits_25', 'habits', 25, 'La Trampa de los Antojos', 'Por qué la industria ultraprocesada diseña comida hiperpalatable que cortocircuita los mecanismos de saciedad.', 'intermediate'),
('habits_26', 'habits', 26, 'Escribe tu "Por Qué"', 'Definir una razón profunda para cambiar tus hábitos que vaya más allá del aspecto estético momentáneo.', 'intermediate'),
('habits_27', 'habits', 27, 'Diario de Progreso', 'Escribir 3 cosas por las que estás agradecido y tus logros de salud al final del día para reconfigurar el cerebro.', 'intermediate'),
('habits_28', 'habits', 28, 'Reducción de Alcohol Social', 'Estrategias para salir de fiesta y divertirse bebiendo menos o alternando vasos de agua entre bebidas.', 'intermediate'),
('habits_29', 'habits', 29, 'El Movimiento Diario (NEAT)', 'Importancia de caminar 8,000-10,000 pasos al día. El NEAT como el mayor quemador de calorías después del metabolismo.', 'intermediate'),
('habits_30', 'habits', 30, 'Tu Círculo Social y Hábitos', 'Cómo el entorno y tus amigos más cercanos influyen directamente en lo que comes y en tu nivel de actividad física.', 'intermediate'),
('habits_31', 'habits', 31, 'Hormonas del Apetito', 'Explicación de la Leptina (hormona de saciedad) y la Grelina (hormona del hambre) y cómo se ven afectadas por el sueño.', 'advanced'),
('habits_32', 'habits', 32, 'Manejo de la Ansiedad Crónica', 'Herramientas cognitivas para canalizar la ansiedad del trabajo sin usar la comida como anestesia emocional.', 'advanced'),
('habits_33', 'habits', 33, 'El Ayuno de Dopamina', 'Reducir el scroll infinito en redes sociales para restablecer la tolerancia de tu cerebro a las cosas aburridas pero sanas.', 'advanced'),
('habits_34', 'habits', 34, 'Higiene Lumínica Avanzada', 'Uso de luces cálidas en casa al anochecer para imitar el atardecer y disparar la producción natural de melatonina.', 'advanced'),
('habits_35', 'habits', 35, 'Terapia de Exposición al Frío', 'Beneficios de las duchas frías en la activación de grasa parda, aumento de dopamina y resistencia mental.', 'advanced'),
('habits_36', 'habits', 36, 'Meditación Mindfulness', 'Cómo practicar la atención plena para observar los antojos como olas que llegan y se van sin reaccionar a ellos.', 'advanced'),
('habits_37', 'habits', 37, 'Fijación de Metas SMART', 'Estructurar tus metas de forma Específica, Medible, Alcanzable, Relevante y con Tiempo definido.', 'advanced'),
('habits_38', 'habits', 38, 'Manejo del Fracaso Temporal', 'Desarrollo de la resiliencia mental cuando tus resultados de peso o masa muscular se estancan.', 'advanced'),
('habits_39', 'habits', 39, 'El Poder de la Rutina Mañanera', 'Cómo estructurar tus primeras 2 horas del día (agua, luz solar, estiramientos) para regular tu energía diaria.', 'advanced'),
('habits_40', 'habits', 40, 'Rutina de Desconexión Nocturna', 'Pasos para preparar al cuerpo para dormir: desconexión digital, lectura, respiración y ambiente fresco.', 'advanced'),
('habits_41', 'habits', 41, 'La Ilusión del Control', 'Aceptar que habrá días fuera de tu control (viajes, emergencias) y aprender a adaptarte en lugar de frustrarte.', 'advanced'),
('habits_42', 'habits', 42, 'Autodisciplina como Autocuidado', 'Reencuadrar la autodisciplina: no es un castigo, es elegir lo que más quieres a largo plazo sobre lo que quieres ahora.', 'advanced'),
('habits_43', 'habits', 43, 'La Parálisis por Análisis', 'Por qué querer hacer la dieta y rutina perfectas desde el día uno te paraliza. Es mejor empezar imperfecto pero constante.', 'advanced'),
('habits_44', 'habits', 44, 'Suplementación de Magnesio', 'Mitos y verdades sobre el Magnesio (Glicinato/Treonato) para mejorar el descanso y relajar el sistema muscular.', 'advanced'),
('habits_45', 'habits', 45, 'Evitar la Fatiga de Decisión', 'Reducir tus decisiones diarias automatizando tus comidas básicas o vistiendo ropa deportiva de forma predeterminada.', 'advanced'),
('habits_46', 'habits', 46, 'La Trampa de los Alimentos Prohibidos', 'Cómo etiquetar la comida como "buena" o "mala" fomenta desórdenes y por qué la flexibilidad es mejor.', 'advanced'),
('habits_47', 'habits', 47, 'El Poder del No', 'Cómo decir no de forma asertiva en eventos sociales ante presiones de comer o beber de forma no saludable.', 'advanced'),
('habits_48', 'habits', 48, 'Evaluación y Auditoría Mensual', 'Cómo revisar tus métricas mensuales (pasos, energía, entrenamientos) para ajustar tu rumbo con compasión.', 'advanced'),
('habits_49', 'habits', 49, 'Comunidad y Accountability', 'La importancia de tener un compañero de entrenamiento o un coach para mantener el compromiso a largo plazo.', 'advanced'),
('habits_50', 'habits', 50, 'Mentalidad del Estilo de Vida', 'El bienestar no es un destino de 28 días, es un sistema de identidad que mantendrás con alegría el resto de tu vida.', 'advanced');
